/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SocialRouteImport } from './routes/social'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MultiplayerIndexRouteImport } from './routes/multiplayer/index'
import { Route as MultiplayerLobbyIdRouteImport } from './routes/multiplayer/$lobbyId'
import { Route as MultiplayerGameLobbyIdRouteImport } from './routes/multiplayer/game/$lobbyId'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerIndexRoute = MultiplayerIndexRouteImport.update({
  id: '/multiplayer/',
  path: '/multiplayer/',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerLobbyIdRoute = MultiplayerLobbyIdRouteImport.update({
  id: '/multiplayer/$lobbyId',
  path: '/multiplayer/$lobbyId',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiplayerGameLobbyIdRoute = MultiplayerGameLobbyIdRouteImport.update({
  id: '/multiplayer/game/$lobbyId',
  path: '/multiplayer/game/$lobbyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/social': typeof SocialRoute
  '/training': typeof TrainingRoute
  '/multiplayer/$lobbyId': typeof MultiplayerLobbyIdRoute
  '/multiplayer': typeof MultiplayerIndexRoute
  '/multiplayer/game/$lobbyId': typeof MultiplayerGameLobbyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/social': typeof SocialRoute
  '/training': typeof TrainingRoute
  '/multiplayer/$lobbyId': typeof MultiplayerLobbyIdRoute
  '/multiplayer': typeof MultiplayerIndexRoute
  '/multiplayer/game/$lobbyId': typeof MultiplayerGameLobbyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz': typeof QuizRoute
  '/social': typeof SocialRoute
  '/training': typeof TrainingRoute
  '/multiplayer/$lobbyId': typeof MultiplayerLobbyIdRoute
  '/multiplayer/': typeof MultiplayerIndexRoute
  '/multiplayer/game/$lobbyId': typeof MultiplayerGameLobbyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/quiz'
    | '/social'
    | '/training'
    | '/multiplayer/$lobbyId'
    | '/multiplayer'
    | '/multiplayer/game/$lobbyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/quiz'
    | '/social'
    | '/training'
    | '/multiplayer/$lobbyId'
    | '/multiplayer'
    | '/multiplayer/game/$lobbyId'
  id:
    | '__root__'
    | '/'
    | '/quiz'
    | '/social'
    | '/training'
    | '/multiplayer/$lobbyId'
    | '/multiplayer/'
    | '/multiplayer/game/$lobbyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizRoute: typeof QuizRoute
  SocialRoute: typeof SocialRoute
  TrainingRoute: typeof TrainingRoute
  MultiplayerLobbyIdRoute: typeof MultiplayerLobbyIdRoute
  MultiplayerIndexRoute: typeof MultiplayerIndexRoute
  MultiplayerGameLobbyIdRoute: typeof MultiplayerGameLobbyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer/': {
      id: '/multiplayer/'
      path: '/multiplayer'
      fullPath: '/multiplayer'
      preLoaderRoute: typeof MultiplayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer/$lobbyId': {
      id: '/multiplayer/$lobbyId'
      path: '/multiplayer/$lobbyId'
      fullPath: '/multiplayer/$lobbyId'
      preLoaderRoute: typeof MultiplayerLobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiplayer/game/$lobbyId': {
      id: '/multiplayer/game/$lobbyId'
      path: '/multiplayer/game/$lobbyId'
      fullPath: '/multiplayer/game/$lobbyId'
      preLoaderRoute: typeof MultiplayerGameLobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizRoute: QuizRoute,
  SocialRoute: SocialRoute,
  TrainingRoute: TrainingRoute,
  MultiplayerLobbyIdRoute: MultiplayerLobbyIdRoute,
  MultiplayerIndexRoute: MultiplayerIndexRoute,
  MultiplayerGameLobbyIdRoute: MultiplayerGameLobbyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
